name: mod-build
on:
  push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK 8
      uses: actions/setup-java@v3.3.0
      with: 
        java-version: '8'
        distribution: 'temurin'
        java-package: jdk
    - uses: actions/checkout@v3.0.2
    - run: |
        wget https://services.gradle.org/distributions/gradle-4.10.2-bin.zip
        unzip gradle-4.10.2-bin.zip
        ./gradle-4.10.2/bin/gradle build --info
        cp ./release/* /opt/libs/
        
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: output
        path: /opt/libs/
